/*!
 * repl.js auto generated by node-repl-tool.js
 * Licensed under the MIT license
 *
 * Copyright (c) 2017 Tony Li
 */
'use strict'

var repl = require('repl');

var replServer = repl.start({
  prompt: '🤖 Jeeves >>> ',
});

var b = require("/Users/atom2ueki/Documents/atom2ueki/node-repl-tool/example/_app/b.js");
replServer.context.b = b;

var a = require("/Users/atom2ueki/Documents/atom2ueki/node-repl-tool/example/a.js");
replServer.context.a = a;
